apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-latest-certificate
  namespace: default
spec:
  dnsNames:
    - aicollaboration.com
    - aicollaboration.net
    - beta.aicollaborationsolutions.aiproduct.io
    - appsmith.aicollaboration.com
    - question-answering.aiproduct.io
    - predictive-basket.aiproduct.io
  secretName: tls-latest-certificate
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
