apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-latest-aiproduct.io
  namespace: default
spec:
  dnsNames:
    - aicollaboration.com
    - appsmith.aicollaboration.com
    - question-answering.aiproduct.io
    - predictive-basket.aiproduct.io
    - '*.aicollaborationsolutions.aiproduct.io'
    - tobiasservice.tobiasoberrauch.aiproduct.io
    - tobiasservice.aicollaborationservices.aiproduct.io
    - foobar.aicollaborationservices.aicollaboration.net
  secretName: tls-latest-aiproduct.io
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
