apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-latest-aiproduct.io
  namespace: default
spec:
  dnsNames:
    - afsdffsabfhjagsd.aicollaborationsolutions.aiproduct.io
    - asfdasd.aicollaborationsolutions.aiproduct.io
  secretName: tls-latest-aiproduct.io
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
